name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - testing-in-ci  # DEBUG

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install gcc gfortran libfftw3-dev libopenmpi-dev ocl-icd-opencl-dev libclfft-dev
      - name: Compile ADDA with `seq`
        run: |
          cd src/
          make seq
      - name: Run `seq` tests
        run: |
          cd tests/2exec
          ./comp2exec seq